# Add dev-only configurations - DEBUG to see more logs when calling upstream services
logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Auto-create/update tables
    show-sql: true      # Show SQL in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        failure-rate-threshold: 60 # 60%
        sliding-window-type: TIME_BASED
        sliding-window-size: 20 # 20 seconds
        minimum-number-of-calls: 100 # 100 calls
        wait-duration-in-open-state: 10s # 10 seconds
